# Generated by Django 4.0.4 on 2023-04-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_data_added_alter_data_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='added',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='published',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
