# Generated by Django 4.0.4 on 2023-04-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_data_relevance_alter_data_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='end_year',
        ),
    ]
