# Generated by Django 4.0.4 on 2023-04-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_data_end_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='end_year',
            field=models.IntegerField(null=True),
        ),
    ]
