# Generated by Django 4.0.4 on 2023-04-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_data_intensity_alter_data_likelihood_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['published']},
        ),
    ]
