# Generated by Django 4.0.4 on 2023-04-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_data_added_alter_data_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='added',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='data',
            name='published',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
        ),
    ]
